steps:

- id: build&push
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker build -t europe-west1-docker.pkg.dev/${PROJECT_ID}/gdg-sousse/gdg-sousse:latest .
    docker push europe-west1-docker.pkg.dev/${PROJECT_ID}/gdg-sousse/gdg-sousse:latest



# id: deploy
# name: 'gcr.io/cloud-builders/gcloud'
# entrypoint: sh
# args:
# '-c'
# |

#       gcloud run deploy gdg-sousse \
#       --region=europe-west1 \
#       --allow-unauthenticated \
#       --image europe-west1-docker.pkg.dev/${PROJECT_ID}/gdg-sousse/gdg-sousse:latest:latest



# options:
#   logging: CLOUD_LOGGING_ONLY 
